{
 "title": "nhl-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average query execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nhl_db_query_duration_seconds_sum[5m])) by (query)\r\n/\r\nsum(rate(nhl_db_query_duration_seconds_count[5m])) by (query)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average HTTP response time over the last 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[10m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "95th-percentile SQL query duration over 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(nhl_db_query_duration_seconds_bucket[10m])) by (le, query)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall requests-per-second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m]))",
     "legendFormat": "Sum over all requests"
    }
   ]
  }
 ]
}